// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYP_fBiUloJptOlPEft-WbT0pS5hXgp4g',
    appId: '1:303735559012:web:8e0cc923853b874ad3e071',
    messagingSenderId: '303735559012',
    projectId: 'aplikasi-gym-palembang',
    authDomain: 'aplikasi-gym-palembang.firebaseapp.com',
    databaseURL: 'https://aplikasi-gym-palembang-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'aplikasi-gym-palembang.firebasestorage.app',
    measurementId: 'G-W6DGR5MZ48',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTRacsynO7qmfTHnLy5peuzk6puA-DimQ',
    appId: '1:303735559012:android:bdedc882a2d573dbd3e071',
    messagingSenderId: '303735559012',
    projectId: 'aplikasi-gym-palembang',
    databaseURL: 'https://aplikasi-gym-palembang-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'aplikasi-gym-palembang.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDYP_fBiUloJptOlPEft-WbT0pS5hXgp4g',
    appId: '1:303735559012:web:c7c658a33445fc4cd3e071',
    messagingSenderId: '303735559012',
    projectId: 'aplikasi-gym-palembang',
    authDomain: 'aplikasi-gym-palembang.firebaseapp.com',
    databaseURL: 'https://aplikasi-gym-palembang-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'aplikasi-gym-palembang.firebasestorage.app',
    measurementId: 'G-W41R3CD7FT',
  );
}
